export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_PRODUCT_DETAILS: "REMOVE_PRODUCT_DETAILS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS"
};
